export enum ActionType {
  MOVE_CELL = 'move_cell',
  DELETE_CELL = 'delete_cell',
  INSERT_CELL_AFTER = 'insert_cell_after',
  UPDATE_CELL = 'update_cell',
  BUNDLE_START = 'buldle_start',
  BUNDLE_COMPLETE = 'bundle_complete',
  DELETE_BUNDLE = 'delete_bundle',
  LOAD_INIT_DATA = 'load_init_data',
  INITIAL_CELL_STATE = 'initial_cell_state',
  INITIAL_BUNDLE_STATE = 'initial_bundle_state',
  SET_THEME = 'set_theme',
  IS_CHANGED = 'is_changed',
  ADD_SERVICE_DATA = 'add_service_data',
}
